def runPyScript(pyScript) {
    env.PROJECT_ROOT = "${USER_HOME}/work/${IMAGE_NAME}"
    sh """docker run --rm \
                     --mount type=volume,src=wca_petition_data,dst=${PROJECT_ROOT}/data \
                     --mount type=volume,src=wca_petition_docs,dst=${PROJECT_ROOT}/docs \
                     ${IMAGE_NAME} python/""" + pyScript
}

pipeline {
    agent any
    triggers {
        cron('H * * * *')
        upstream(upstreamProjects: "petition-stats-docker-build",
                 threshold: hudson.model.Result.SUCCESS)
    }
    options {
        lock resource: 'Petition'
    }
    environment {
        IMAGE_NAME = 'petition-stats'
        USER_HOME = '/home/jovyan'
    }
    stages {
        stage('Refresh Reports') {
            steps {
                runPyScript('Petition_Reports.py')
            }
        }
    }
    post {
        failure {
            emailext(
                to: "${EMAIL_RECIPIENTS}",
                subject: "Failed Build: ${currentBuild.fullDisplayName}.",
                body: """<p>FAILURE: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'</p>
                         <p>See attachment for console output or visit this
                            <a href=\"${env.BUILD_URL}\">link</a>.</p>""",
                attachLog: true
            )
        }
    }
}
